import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function AppLayout({ children }) {
  const session = await getServerSession(authOptions);

  if (!session) redirect("/");

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen">
          <aside className="bg-blue-100 w-48 p-4">
            aside stuff
            <div>
              <Image
                src={session?.user.image}
                alt={session.user.name}
                width={64}
                height={64}
              />
            </div>
          </aside>
          <div className="max-w-4xl w-full border p-6">{children}</div>
        </main>
      </body>
    </html>
  );
}
