import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faChartLine,
  faFileLines,
  faGear,
  faPaperclip,
  faRightFromBracket,
} from "@fortawesome/free-solid-svg-icons";
import LogoutButton from "@/components/header/LogoutButton";
import Provider from "@/components/Provider";
import mongoose from "mongoose";
import { Page } from "@/models/Page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function AppLayout({ children }) {
  const session = await getServerSession(authOptions);

  if (!session) redirect("/");

  mongoose.connect(process.env.MONGODB_URI);
  const page = await Page.findOne({ uri: "" });

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <main className="flex min-h-screen">
            <aside className="bg-blue-100 w-48 p-4 shadow">
              <div className="border-2 rounded-full w-16 mx-auto overflow-hidden">
                <Image
                  src={session?.user.image}
                  alt={session.user.name}
                  width={98}
                  height={98}
                  className="object-contain shadow-lg"
                />
              </div>

              <nav className="flex flex-col gap-4 mt-10 text-center text-gray-500">
                <Link
                  href={"/my-page"}
                  className="flex items-center gap-4 justify-start"
                >
                  <FontAwesomeIcon icon={faFileLines} className="w-4" />
                  <span className="text-gray-700">My Page</span>
                </Link>
                <Link
                  href={`/account/[account]/analytics`}
                  className="flex items-center gap-4 justify-start"
                >
                  <FontAwesomeIcon icon={faChartLine} className="w-4" />
                  <span className="text-gray-700">Analytics</span>
                </Link>
                <Link
                  href={"/settings"}
                  className="flex items-center gap-4 justify-start"
                >
                  <FontAwesomeIcon icon={faGear} className="w-4" />
                  <span className="text-gray-700">Settings</span>
                </Link>

                {/* logout button */}
                <LogoutButton
                  iconLeft={true}
                  className="flex gap-4 justify-start items-center"
                />
              </nav>
            </aside>
            <div className="w-full">
              <div className="m-4 p-4 bg-white shadow">{children}</div>
            </div>
          </main>
        </Provider>
      </body>
    </html>
  );
}
