import { Lato } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import Provider from "@/components/Provider";
import AppSideNav from "@/components/appLayout/AppSideNav";
import { Toaster } from "react-hot-toast";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function AppLayout({ children, ...rest }) {
  const session = await getServerSession(authOptions);

  if (!session) redirect("/");

  // fix this
  // mongoose.connect(process.env.MONGODB_URI);
  // const page = await Page.findOne({ uri: "" });

  return (
    <html lang="en">
      <body className={lato.className}>
        <Provider>
          <Toaster />
          <main className="flex min-h-screen">
            <aside className="bg-blue-100 w-48 p-4 shadow">
              <div className="border-2 rounded-full w-16 mx-auto overflow-hidden">
                <Image
                  src={session?.user.image}
                  alt={session?.user.name}
                  width={98}
                  height={98}
                  className="object-contain shadow-lg"
                />
              </div>

              <AppSideNav />
            </aside>
            <div className="w-full">
              <div className="m-4 p-4 bg-white shadow">{children}</div>
            </div>
          </main>
        </Provider>
      </body>
    </html>
  );
}
